# Generated by Django 2.1 on 2019-04-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('berth_preference', models.CharField(max_length=256)),
                ('rac_seats', models.CharField(max_length=10)),
                ('waiting_list', models.CharField(max_length=10)),
            ],
        ),
    ]
